stages:
  - main-build

variables:
  GIT_DEPTH: "1"
  CONTAINER_REGISTRY: voxsoft/google-fluentd-sidecar

default:
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    # Get latest release of google-fluentd
    - apk add curl
    - export RELEASE=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/GoogleCloudPlatform/google-fluentd/releases/latest | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
    # Enable experimental feature to be able to inspect remote images
    - 'mkdir -p ~/.docker && echo ''{"experimental": "enabled"}'' > ~/.docker/config.json'
    # Authenticate to Container Registry
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD

Build Main Image:
  stage: main-build
  script:
    # Stop if image already exists
    - |
      if [ $FORCE_REBUILD == "true" ]
        then echo -e "\e[41mImage Rebuild Forced!\e[0m"
        else docker manifest inspect ${CONTAINER_REGISTRY}:${RELEASE} > /dev/null && echo "Version ${RELEASE} is already exists" && exit 0
      fi
    # Build container image
    - docker build -t ${CONTAINER_REGISTRY}:${RELEASE} . 
    # Additional tags for container image
    - docker tag ${CONTAINER_REGISTRY}:${RELEASE}
      ${CONTAINER_REGISTRY}:latest
    # Push all tags
    - docker push ${CONTAINER_REGISTRY}:${RELEASE}
    - docker push ${CONTAINER_REGISTRY}:latest
